"""Run the impact engine against the live seeded pipeline and emit a drift report artifact.

Usage: ./.venv/bin/python scripts/demo_impact.py
Writes examples/margin_haircut_impact.md and prints the summaries.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # make `engine` importable

from datahub.ingestion.graph.client import DataHubGraph, DatahubClientConfig

from engine.config import DataHubConfig
from engine.impact import analyze
from engine.lineage_graph import ColumnLineageGraph
from engine.models import ChangeType, ColumnRef, SchemaChange

COLL = "urn:li:dataset:(urn:li:dataPlatform:snowflake,broker.raw.collateral,PROD)"
REPORT = "urn:li:dataset:(urn:li:dataPlatform:snowflake,broker.marts.margin_report,PROD)"


def render(report) -> str:
    lines = [
        f"### {report.change.change_type.value.upper()} — `{report.change.column}`",
        "",
        f"- **Severity:** `{report.severity}`",
        f"- **Detail:** {report.change.detail or '—'}",
        f"- **Breaks {len(report.affected)} report column(s):**",
    ]
    for a in sorted(report.affected, key=lambda x: str(x.column)):
        lines.append(f"  - `{a.column}`  ⟵ `{a.transform}`  _(hop {a.hops})_")
    return "\n".join(lines)


def main() -> None:
    cfg = DataHubConfig()
    client = DataHubGraph(DatahubClientConfig(server=cfg.gms_url))
    graph = ColumnLineageGraph.from_datahub(client, REPORT)

    scenarios = [
        SchemaChange(ColumnRef(COLL, "haircut_pct"), ChangeType.DROPPED,
                     detail="Upstream team removed collateral.haircut_pct."),
        SchemaChange(ColumnRef(COLL, "haircut_pct"), ChangeType.RETYPED,
                     detail="haircut_pct changed from percent (0-100) to fraction (0-1)."),
    ]

    blocks = ["# Drift Sentinel — Margin Report Impact\n",
              "Generated by the deterministic impact engine over live DataHub lineage.\n"]
    for change in scenarios:
        report = analyze(change, graph)
        print(report.summary())
        blocks.append(render(report))
        blocks.append("")

    out = Path(__file__).resolve().parent.parent / "examples" / "margin_haircut_impact.md"
    out.write_text("\n".join(blocks))
    print(f"\nwrote {out.relative_to(out.parent.parent)}")


if __name__ == "__main__":
    main()
